
import { GPUData } from './types';

export const APP_NAME = "GPU Pass";

export const MOCK_GPUS: GPUData[] = [
  {
    id: 'gpu-h100-sxm5-001',
    imageUrl: 'https://images.unsplash.com/photo-1624701928517-44c8ac49d93c?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'NVIDIA',
    model: 'H100 80GB HBM3',
    serialNumber: 'H100-SXM5-29384712',
    formFactor: 'SXM',
    productionYear: 2023,
    firmwareVersion: '96.00.12.00.01',
    status: 'active',
    numberOfPreviousOwners: 1,
    ownerHistory: [
      { ownerType: 'manufacturer', startDate: '2023-01-10', endDate: '2023-02-15', location: 'Hsinchu, TW' },
      { ownerType: 'cloud_provider', startDate: '2023-03-01', endDate: 'current', location: 'Ashburn, VA (Hyperscale DC)' }
    ],
    totalTimeInServiceMonths: 21,
    workloadSplit: { trainingPercent: 92, inferencePercent: 5, idlePercent: 3 },
    avgGpuUtilizationPercent: 88,
    peakGpuUtilizationPercent: 100,
    fullLoadHours: 14200,
    estimatedLifespanHours: 50000, 
    typicalJobDuration: 'Long (>24h)',
    avgTempCelsius: 72,
    maxTempCelsius: 85,
    thermalCyclesCount: 42,
    avgPowerDrawWatts: 680,
    peakPowerDrawWatts: 700,
    powerSpikeEventsCount: 8,
    avgEfficiencyTflopsPerWatt: 20.2,
    hbmEccCorrectedErrors: 1240, 
    hbmEccUncorrectedErrors: 0, 
    throttlingEventsCount: 14,
    driverResetEvents: 2,
    repairsPerformed: [],
    firmwareModified: false,
    undervoltedOrOverclocked: false,
    healthScore: 91,
    secondLifeCategory: 'A_training_ready',
    strategicRecommendations: [
      { title: 'Fine-Tuning Cluster', description: 'Certified for high-precision model fine-tuning.', suitability: 98 },
      { title: 'Inference Node', description: 'Highly stable for real-time inference.', suitability: 95 }
    ],
    materialComposition: [
      { name: 'Copper', symbol: 'Cu', percentage: 22.4, impact: 'low' },
      { name: 'Gold', symbol: 'Au', percentage: 0.12, impact: 'critical' }
    ],
    carbonMetrics: [
      { phase: 'Manufacturing', kgCo2: 150 },
      { phase: 'Operational', kgCo2: 660 }
    ],
    priceUsd: 32000
  },
  {
    id: 'gpu-a100-sxm-002',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'NVIDIA',
    model: 'A100 80GB Tensor Core',
    serialNumber: 'A100-SXM4-13245232',
    formFactor: 'SXM',
    productionYear: 2021,
    firmwareVersion: '94.00.51.00.01',
    status: 'standby',
    numberOfPreviousOwners: 2,
    ownerHistory: [
      { ownerType: 'cloud_provider', startDate: '2021-06-01', endDate: '2023-01-15', location: 'Frankfurt, DE' },
      { ownerType: 'research_lab', startDate: '2023-02-01', endDate: 'current', location: 'Munich, DE' }
    ],
    totalTimeInServiceMonths: 42,
    workloadSplit: { trainingPercent: 60, inferencePercent: 30, idlePercent: 10 },
    avgGpuUtilizationPercent: 74,
    peakGpuUtilizationPercent: 98,
    fullLoadHours: 22800,
    estimatedLifespanHours: 60000,
    typicalJobDuration: 'Medium (1-24h)',
    avgTempCelsius: 65,
    maxTempCelsius: 78,
    thermalCyclesCount: 230,
    avgPowerDrawWatts: 340,
    peakPowerDrawWatts: 400,
    powerSpikeEventsCount: 15,
    avgEfficiencyTflopsPerWatt: 9.4,
    hbmEccCorrectedErrors: 3100,
    hbmEccUncorrectedErrors: 1,
    throttlingEventsCount: 5,
    driverResetEvents: 1,
    repairsPerformed: ['Thermal Interface Material replacement (2023)'],
    firmwareModified: false,
    undervoltedOrOverclocked: false,
    healthScore: 78,
    secondLifeCategory: 'B_inference_and_light_training',
    strategicRecommendations: [
      { title: 'Batch Inference', description: 'Recommended for heavy inference-only tasks.', suitability: 92 }
    ],
    materialComposition: [
      { name: 'Copper', symbol: 'Cu', percentage: 24.1, impact: 'low' }
    ],
    carbonMetrics: [
      { phase: 'Manufacturing', kgCo2: 120 },
      { phase: 'Operational', kgCo2: 480 }
    ],
    priceUsd: 18500
  },
  {
    id: 'gpu-l40s-pcie-003',
    imageUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'NVIDIA',
    model: 'L40S 48GB GDDR6',
    serialNumber: 'L40S-PCIE-992211',
    formFactor: 'PCIe',
    productionYear: 2024,
    firmwareVersion: '95.00.44.00.01',
    status: 'active',
    numberOfPreviousOwners: 0,
    ownerHistory: [
      { ownerType: 'enterprise', startDate: '2024-03-15', endDate: 'current', location: 'Dublin, IE' }
    ],
    totalTimeInServiceMonths: 9,
    workloadSplit: { trainingPercent: 10, inferencePercent: 85, idlePercent: 5 },
    avgGpuUtilizationPercent: 45,
    peakGpuUtilizationPercent: 88,
    fullLoadHours: 1200,
    estimatedLifespanHours: 70000,
    typicalJobDuration: 'Short (<1h)',
    avgTempCelsius: 58,
    maxTempCelsius: 68,
    thermalCyclesCount: 12,
    avgPowerDrawWatts: 280,
    peakPowerDrawWatts: 350,
    powerSpikeEventsCount: 2,
    avgEfficiencyTflopsPerWatt: 15.5,
    hbmEccCorrectedErrors: 50,
    hbmEccUncorrectedErrors: 0,
    throttlingEventsCount: 0,
    driverResetEvents: 0,
    repairsPerformed: [],
    firmwareModified: false,
    undervoltedOrOverclocked: false,
    healthScore: 98,
    secondLifeCategory: 'A_training_ready',
    strategicRecommendations: [{ title: 'Omniverse Node', description: 'Ideal for real-time 3D and rendering.', suitability: 100 }],
    materialComposition: [{ name: 'Silver', symbol: 'Ag', percentage: 0.3, impact: 'medium' }],
    carbonMetrics: [{ phase: 'Manufacturing', kgCo2: 90 }, { phase: 'Operational', kgCo2: 180 }],
    priceUsd: 12500
  },
  {
    id: 'gpu-mi300x-oam-004',
    imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'AMD',
    model: 'Instinct MI300X 192GB HBM3',
    serialNumber: 'MI300X-OAM-000188',
    formFactor: 'SXM',
    productionYear: 2024,
    firmwareVersion: 'MI300X-1.0.4',
    status: 'active',
    numberOfPreviousOwners: 1,
    ownerHistory: [
      { ownerType: 'manufacturer', startDate: '2023-12-01', endDate: '2024-01-10', location: 'Austin, TX' },
      { ownerType: 'cloud_provider', startDate: '2024-02-01', endDate: 'current', location: 'Palo Alto, CA' }
    ],
    totalTimeInServiceMonths: 10,
    workloadSplit: { trainingPercent: 95, inferencePercent: 2, idlePercent: 3 },
    avgGpuUtilizationPercent: 92,
    peakGpuUtilizationPercent: 100,
    fullLoadHours: 6500,
    estimatedLifespanHours: 45000,
    typicalJobDuration: 'Long (>24h)',
    avgTempCelsius: 75,
    maxTempCelsius: 82,
    thermalCyclesCount: 55,
    avgPowerDrawWatts: 720,
    peakPowerDrawWatts: 750,
    powerSpikeEventsCount: 22,
    avgEfficiencyTflopsPerWatt: 18.8,
    hbmEccCorrectedErrors: 4500,
    hbmEccUncorrectedErrors: 0,
    throttlingEventsCount: 32,
    driverResetEvents: 4,
    repairsPerformed: [],
    firmwareModified: true,
    undervoltedOrOverclocked: true,
    healthScore: 89,
    secondLifeCategory: 'A_training_ready',
    strategicRecommendations: [{ title: 'Large Scale Training', description: 'High bandwidth memory efficiency for LLMs.', suitability: 94 }],
    materialComposition: [{ name: 'Rare Earth', symbol: 'RE', percentage: 1.5, impact: 'critical' }],
    carbonMetrics: [{ phase: 'Manufacturing', kgCo2: 180 }, { phase: 'Operational', kgCo2: 820 }],
    priceUsd: 28000
  },
  {
    id: 'gpu-a100-pcie-005',
    imageUrl: 'https://images.unsplash.com/photo-1540655037529-dec987208707?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'NVIDIA',
    model: 'A100 40GB PCIe',
    serialNumber: 'A100-PCIE-772211',
    formFactor: 'PCIe',
    productionYear: 2020,
    firmwareVersion: '92.00.32.00.01',
    status: 'active',
    numberOfPreviousOwners: 2,
    ownerHistory: [
      { ownerType: 'cloud_provider', startDate: '2020-05-01', endDate: '2022-04-01', location: 'Chicago, IL' },
      { ownerType: 'enterprise', startDate: '2022-05-01', endDate: 'current', location: 'Seattle, WA' }
    ],
    totalTimeInServiceMonths: 54,
    workloadSplit: { trainingPercent: 20, inferencePercent: 60, idlePercent: 20 },
    avgGpuUtilizationPercent: 55,
    peakGpuUtilizationPercent: 90,
    fullLoadHours: 35000,
    estimatedLifespanHours: 50000,
    typicalJobDuration: 'Medium (1-24h)',
    avgTempCelsius: 62,
    maxTempCelsius: 74,
    thermalCyclesCount: 410,
    avgPowerDrawWatts: 220,
    peakPowerDrawWatts: 250,
    powerSpikeEventsCount: 30,
    avgEfficiencyTflopsPerWatt: 8.1,
    hbmEccCorrectedErrors: 8900,
    hbmEccUncorrectedErrors: 2,
    throttlingEventsCount: 18,
    driverResetEvents: 12,
    repairsPerformed: ['PCB cleaning (2022)'],
    firmwareModified: false,
    undervoltedOrOverclocked: false,
    healthScore: 62,
    secondLifeCategory: 'C_inference_only',
    strategicRecommendations: [{ title: 'Legacy Inference', description: 'Budget friendly for non-critical workloads.', suitability: 85 }],
    materialComposition: [{ name: 'Silicon', symbol: 'Si', percentage: 14.2, impact: 'medium' }],
    carbonMetrics: [{ phase: 'Manufacturing', kgCo2: 110 }, { phase: 'Operational', kgCo2: 900 }],
    priceUsd: 6500
  },
  {
    id: 'gpu-h100-pcie-006',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'NVIDIA',
    model: 'H100 80GB PCIe',
    serialNumber: 'H100-PCIE-112233',
    formFactor: 'PCIe',
    productionYear: 2023,
    firmwareVersion: '96.00.22.00.01',
    status: 'active',
    numberOfPreviousOwners: 1,
    ownerHistory: [
      { ownerType: 'manufacturer', startDate: '2023-05-01', endDate: '2023-06-01', location: 'Hsinchu, TW' },
      { ownerType: 'research_lab', startDate: '2023-07-01', endDate: 'current', location: 'Paris, FR' }
    ],
    totalTimeInServiceMonths: 18,
    workloadSplit: { trainingPercent: 80, inferencePercent: 15, idlePercent: 5 },
    avgGpuUtilizationPercent: 82,
    peakGpuUtilizationPercent: 99,
    fullLoadHours: 11000,
    estimatedLifespanHours: 50000,
    typicalJobDuration: 'Long (>24h)',
    avgTempCelsius: 68,
    maxTempCelsius: 80,
    thermalCyclesCount: 35,
    avgPowerDrawWatts: 350,
    peakPowerDrawWatts: 380,
    powerSpikeEventsCount: 5,
    avgEfficiencyTflopsPerWatt: 19.5,
    hbmEccCorrectedErrors: 420,
    hbmEccUncorrectedErrors: 0,
    throttlingEventsCount: 4,
    driverResetEvents: 0,
    repairsPerformed: [],
    firmwareModified: false,
    undervoltedOrOverclocked: false,
    healthScore: 94,
    secondLifeCategory: 'A_training_ready',
    strategicRecommendations: [{ title: 'ML Ops Cluster', description: 'Perfect for mid-size enterprise training.', suitability: 96 }],
    materialComposition: [{ name: 'Rare Earth', symbol: 'RE', percentage: 1.1, impact: 'critical' }],
    carbonMetrics: [{ phase: 'Manufacturing', kgCo2: 140 }, { phase: 'Operational', kgCo2: 550 }],
    priceUsd: 29500
  },
  {
    id: 'gpu-l40s-pcie-007',
    imageUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'NVIDIA',
    model: 'L40S 48GB GDDR6',
    serialNumber: 'L40S-PCIE-000888',
    formFactor: 'PCIe',
    productionYear: 2023,
    firmwareVersion: '95.00.22.00.01',
    status: 'active',
    numberOfPreviousOwners: 0,
    ownerHistory: [
      { ownerType: 'edge_provider', startDate: '2023-11-01', endDate: 'current', location: 'London, UK' }
    ],
    totalTimeInServiceMonths: 14,
    workloadSplit: { trainingPercent: 5, inferencePercent: 90, idlePercent: 5 },
    avgGpuUtilizationPercent: 40,
    peakGpuUtilizationPercent: 75,
    fullLoadHours: 4200,
    estimatedLifespanHours: 70000,
    typicalJobDuration: 'Short (<1h)',
    avgTempCelsius: 52,
    maxTempCelsius: 60,
    thermalCyclesCount: 88,
    avgPowerDrawWatts: 240,
    peakPowerDrawWatts: 260,
    powerSpikeEventsCount: 1,
    avgEfficiencyTflopsPerWatt: 16.2,
    hbmEccCorrectedErrors: 12,
    hbmEccUncorrectedErrors: 0,
    throttlingEventsCount: 0,
    driverResetEvents: 0,
    repairsPerformed: [],
    firmwareModified: false,
    undervoltedOrOverclocked: false,
    healthScore: 99,
    secondLifeCategory: 'A_training_ready',
    strategicRecommendations: [{ title: 'VDI & Rendering', description: 'Virtually new. Perfect for edge compute.', suitability: 100 }],
    materialComposition: [{ name: 'Silver', symbol: 'Ag', percentage: 0.35, impact: 'medium' }],
    carbonMetrics: [{ phase: 'Manufacturing', kgCo2: 90 }, { phase: 'Operational', kgCo2: 240 }],
    priceUsd: 13200
  },
  {
    id: 'gpu-mi300x-oam-008',
    imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'AMD',
    model: 'Instinct MI300X 192GB HBM3',
    serialNumber: 'MI300X-OAM-000999',
    formFactor: 'SXM',
    productionYear: 2024,
    firmwareVersion: 'MI300X-1.0.5',
    status: 'active',
    numberOfPreviousOwners: 0,
    ownerHistory: [
      { ownerType: 'enterprise', startDate: '2024-05-01', endDate: 'current', location: 'San Jose, CA' }
    ],
    totalTimeInServiceMonths: 7,
    workloadSplit: { trainingPercent: 98, inferencePercent: 1, idlePercent: 1 },
    avgGpuUtilizationPercent: 95,
    peakGpuUtilizationPercent: 100,
    fullLoadHours: 4800,
    estimatedLifespanHours: 45000,
    typicalJobDuration: 'Long (>24h)',
    avgTempCelsius: 78,
    maxTempCelsius: 86,
    thermalCyclesCount: 22,
    avgPowerDrawWatts: 750,
    peakPowerDrawWatts: 820,
    powerSpikeEventsCount: 45,
    avgEfficiencyTflopsPerWatt: 18.2,
    hbmEccCorrectedErrors: 2100,
    hbmEccUncorrectedErrors: 0,
    throttlingEventsCount: 52,
    driverResetEvents: 8,
    repairsPerformed: [],
    firmwareModified: false,
    undervoltedOrOverclocked: true,
    healthScore: 92,
    secondLifeCategory: 'A_training_ready',
    strategicRecommendations: [{ title: 'LLM Cluster', description: 'Massive memory bandwidth for giant models.', suitability: 97 }],
    materialComposition: [{ name: 'Rare Earth', symbol: 'RE', percentage: 1.5, impact: 'critical' }],
    carbonMetrics: [{ phase: 'Manufacturing', kgCo2: 180 }, { phase: 'Operational', kgCo2: 520 }],
    priceUsd: 31000
  },
  {
    id: 'gpu-a100-sxm-009',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'NVIDIA',
    model: 'A100 80GB SXM4',
    serialNumber: 'A100-SXM4-000123',
    formFactor: 'SXM',
    productionYear: 2022,
    firmwareVersion: '94.00.51.00.01',
    status: 'active',
    numberOfPreviousOwners: 1,
    ownerHistory: [
      { ownerType: 'cloud_provider', startDate: '2022-01-01', endDate: '2023-12-31', location: 'Tokyo, JP' },
      { ownerType: 'research_lab', startDate: '2024-01-01', endDate: 'current', location: 'Kyoto, JP' }
    ],
    totalTimeInServiceMonths: 34,
    workloadSplit: { trainingPercent: 70, inferencePercent: 20, idlePercent: 10 },
    avgGpuUtilizationPercent: 68,
    peakGpuUtilizationPercent: 95,
    fullLoadHours: 18000,
    estimatedLifespanHours: 60000,
    typicalJobDuration: 'Medium (1-24h)',
    avgTempCelsius: 64,
    maxTempCelsius: 75,
    thermalCyclesCount: 155,
    avgPowerDrawWatts: 380,
    peakPowerDrawWatts: 420,
    powerSpikeEventsCount: 12,
    avgEfficiencyTflopsPerWatt: 10.1,
    hbmEccCorrectedErrors: 1200,
    hbmEccUncorrectedErrors: 0,
    throttlingEventsCount: 8,
    driverResetEvents: 1,
    repairsPerformed: [],
    firmwareModified: false,
    undervoltedOrOverclocked: false,
    healthScore: 88,
    secondLifeCategory: 'A_training_ready',
    strategicRecommendations: [{ title: 'Academic Research', description: 'Highly efficient for parallel computing.', suitability: 95 }],
    materialComposition: [{ name: 'Gold', symbol: 'Au', percentage: 0.14, impact: 'critical' }],
    carbonMetrics: [{ phase: 'Manufacturing', kgCo2: 120 }, { phase: 'Operational', kgCo2: 410 }],
    priceUsd: 19800
  },
  {
    id: 'gpu-h100-sxm5-010',
    imageUrl: 'https://images.unsplash.com/photo-1624701928517-44c8ac49d93c?q=80&w=1000&auto=format&fit=crop',
    manufacturer: 'NVIDIA',
    model: 'H100 80GB HBM3',
    serialNumber: 'H100-SXM5-000444',
    formFactor: 'SXM',
    productionYear: 2023,
    firmwareVersion: '96.00.12.00.01',
    status: 'active',
    numberOfPreviousOwners: 1,
    ownerHistory: [
      { ownerType: 'manufacturer', startDate: '2023-08-01', endDate: '2023-09-01', location: 'Hsinchu, TW' },
      { ownerType: 'cloud_provider', startDate: '2023-09-15', endDate: 'current', location: 'Singapore, SG' }
    ],
    totalTimeInServiceMonths: 15,
    workloadSplit: { trainingPercent: 88, inferencePercent: 10, idlePercent: 2 },
    avgGpuUtilizationPercent: 85,
    peakGpuUtilizationPercent: 99,
    fullLoadHours: 9800,
    estimatedLifespanHours: 50000,
    typicalJobDuration: 'Long (>24h)',
    avgTempCelsius: 70,
    maxTempCelsius: 83,
    thermalCyclesCount: 38,
    avgPowerDrawWatts: 670,
    peakPowerDrawWatts: 700,
    powerSpikeEventsCount: 6,
    avgEfficiencyTflopsPerWatt: 20.1,
    hbmEccCorrectedErrors: 850,
    hbmEccUncorrectedErrors: 0,
    throttlingEventsCount: 10,
    driverResetEvents: 1,
    repairsPerformed: [],
    firmwareModified: false,
    undervoltedOrOverclocked: false,
    healthScore: 93,
    secondLifeCategory: 'A_training_ready',
    strategicRecommendations: [
      { title: 'Fine-Tuning Cluster', description: 'Certified for high-precision model fine-tuning.', suitability: 97 },
      { title: 'Inference Node', description: 'Highly stable for real-time inference.', suitability: 96 }
    ],
    materialComposition: [
      { name: 'Copper', symbol: 'Cu', percentage: 22.4, impact: 'low' },
      { name: 'Gold', symbol: 'Au', percentage: 0.12, impact: 'critical' }
    ],
    carbonMetrics: [
      { phase: 'Manufacturing', kgCo2: 150 },
      { phase: 'Operational', kgCo2: 580 }
    ],
    priceUsd: 31500
  }
];
